### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by peterood**

### CODE REVIEW

**Comment by peterood** [comment]
@googlebot my CLA has been submitted.

**Comment by PaulKinlan** [comment]
Thanks!

**Comment by PaulKinlan** [comment]
This should be in staging in a couple of minutes, we will push live later in the week.

**Comment by peterood** [comment]
@PaulKinlan Great, thanks! Because the different html files are sharing copy there are related typos in 

[firstbreakpoint.html](https://github.com/googlesamples/web-fundamentals/blob/gh-pages/samples/getting-started/your-first-multi-screen-site/firstbreakpoint.html)
[fixingfirstbreakpoint.html](https://github.com/googlesamples/web-fundamentals/blob/gh-pages/samples/getting-started/your-first-multi-screen-site/fixingfirstbreakpoint.html)

"The worlds leading mobile web developers" should be "The world's leading mobile web developers"

I thought multiple pull requests might get redundant. Please let me know if that's preferred though.

**Comment by PaulKinlan** [comment]
Actually..... I need to go back and check this. This might be auto pushed
from the webfundentals directory....

**Pull request merged**
